language: ruby
cache: bundler
deploy:
  edge: true
  provider: cloudfoundry
  username: leung.andrew@gmail.com
  api: https://api.run.pivotal.io
  organization: andrew
  space: labs-sydney-beach
  password:
    secure: z4bvuXcrIt9uX3GHM2CEPOeDOKgnSLwGeHvg5Y/1cTlSS+4ainQLFcN8BSFF2+aUiQ3iNdAT/yjQRVcgW2GDpFTrvpOhuV1dWqYORbsQ/bkiqb3QkOKLBEX+XVfZIg2N/SGaOWXYPD+eJ6iGWZ6aYwcBQL3mJbdCt8MCq/UFr+joorROi//r2Q7QMCoAWbE0fL0VQyPJzQo+A15FfkTutUTMgrTdfgfby5kqGRxS7hFB7mo6Tmm6CCANRnVPOB0fdtLkt5/MuITUNdcvWvjaN1bJ5HNakXG9YXHZ9uHlJfZhGyh2Y7NIQIsBTPPc3KQogFMmKSr38eafb6cvdQTWIYtujo4YV4zm4/czWDioXf8fAi50Ul7505LFgR3hf075x0XkYRZofs4lGB7Hyh0oiEYMzcmIEN6IqgRS2Q9LTKamwGAeB0qLxAC28hn7VApq8U3WX65rIDnBeKB1KKG5+cVyWnByxP6mMRjHXBKfo7dQD+2LtOKd6RjekOhmBbGyBTYHA2lJAbIqOX2H4MSqG6kMWoM2eGfK1O5q5SCKCBPjysh+ntemzmkKwYjsEPW8HXfs3wHu86rAZmW9J1leI1LfcQK5oagolvOwUcm8ynepj89lhawJnpTev3X1jkicWWjDTOTKwwZHsn312RdF5HWNIsbDL6ndXofi8w3Iz/A=
services:
  - postgresql
before_script:
  - psql -c 'create database project_test;' -U postgres
