language: ruby
cache: bundler
deploy:
  edge: true
  provider: cloudfoundry
  username: labs-sydney-devs-todolist@googlegroups.com
  api: https://api.run.pivotal.io
  organization: labs-sydney-beach
  space: development
  password:
    secure: JpQBF+IMaYVt+r6CUbYNeMv/arkd3j5QWcaqsGgQ+D3BCqoP5/FxZkl8jIfjLe0H27xcuAYlFzKP9NH4P7GlBX9zZ8Vs84ZT6jAGHLn1ATY8nqIk73z/HIdKIh4biTF92jgztXqaNtEtzqP3rWT5OLMuM0MCQr1jb9OOds6CANLvXIQxNnyPK2+Klb7ze+YvTQF3in9j6Kq8MPKaPC/Ik5wEhWdsS2G+s7ZoEqJZgEZ8fhcUN6U8OFWEaJVxieNlWFeuLtzY/v0twZzVI4JT25nXKLTD44F71b15Jt23EJiT0vblxmL/pI0bydpl6lTK+Z5AdY+ZPxbX4y10I2CfTlD1ZEpXEBSV2Z495jYdXg2AVnB0iZIc+dFZLYTtULS0c1Vzff3LjrNxHRAvJz+IwYy9B0st7Ph5CmxTVQHnpwm+1Q33bMD/RERv8AIjzTKW9m3lXru2/evZkVSKjxV24o5m7OwV3lsTwCIfwbiZE7HDicOZJQNdqHQSs3Q2/ifTpGtl1mtkGloRMl7ercoycPYgFuR4nafLc2145sItbfTAiE31vgTn0Ea+K2DQxvjSLxEorLq1nHMxDkmM3k3A2dCEvzJMwJJ5shobmX43/y528k/XxfSDluY2eELrn/YOcYle4Khkvm8vRGvRPyOoCnNQfhfsilBRawFGjLZHM6s=
services:
- postgresql
before_script:
- psql -c 'create database project_test;' -U postgres
