language: ruby
cache: bundler
deploy:
  edge: true
  provider: cloudfoundry
  username: labs-sydney-devs-todolist@googlegroups.com
  api: https://api.run.pivotal.io
  organization: labs-sydney-beach
  space: development
  password:
    secure: chdbdo4cWeMXCVQuJpLQ8f5QswTNzyIvEkfoTEkm28wvHYLTPgxpJkmHYe6lt5aqoJyJh+UE0e51MIVZXUYLQI7WFdAEvVgEMj57xeZohOrRACJ5GNkb1lXn0wRP5co6CJeLhgi3pX2shozSON0I0i+2fwhHjywecmqR+F+iRGu/OqhbvnnmXTrOQkWz795MSI4NkUuW+EcQgLzIog9DFaPKaEkuInEXLIKe71TOmNl5/VRIhDIZ9RxpbnpKUF+8P9PaIslilZ48yTjY1uQN1mzQlTMnv1CdjAMbsUT9uP/5kRa92DXtkWJBoD3lN6tKiZK0pzhHWP9pnwPTLGULwR9ktQ8Mwx7AR1LNwUdix+OY+krIMBQxEJ6LYERGFtkfgn3GSkMIk0fR7B0JHJ6jLImBKKIWV3RPBleNZgavlOCLGG/Fy+dDYOjZ++ySylBsYFOCYF+yCqADWzEtRAkmdsM3PMVgAA6IUZ094lyNXvgrO4iyE6eNWiJ83XA8BjP4bboWu3d6qlYhpkPm9Tsmi8KYhV+MKW9WcpAMPpXSIE1x8rD8J4RDMgu/7cvxQEeZFVbrqpT80nIbjpNY4XpGb58ncWlhcBHCsyQkh3qSlkjeGVNLDMauCHgLjXIO6glPx/4pmnk1S3ayAjF3S1zNpOUibKl1jP5Yv2UOXjMGyDs=
services:
- postgresql
before_script:
- psql -c 'create database project_test;' -U postgres
